/*
 * Fever Providers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.fever.events.primary.api;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * EventSummary
 */
@JsonPropertyOrder({
  EventSummary.JSON_PROPERTY_ID,
  EventSummary.JSON_PROPERTY_TITLE,
  EventSummary.JSON_PROPERTY_START_DATE,
  EventSummary.JSON_PROPERTY_START_TIME,
  EventSummary.JSON_PROPERTY_END_DATE,
  EventSummary.JSON_PROPERTY_END_TIME,
  EventSummary.JSON_PROPERTY_MIN_PRICE,
  EventSummary.JSON_PROPERTY_MAX_PRICE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen")
public class EventSummary   {
  public static final String JSON_PROPERTY_ID = "id";
  @JsonProperty(JSON_PROPERTY_ID)
  private UUID id;

  public static final String JSON_PROPERTY_TITLE = "title";
  @JsonProperty(JSON_PROPERTY_TITLE)
  private String title;

  public static final String JSON_PROPERTY_START_DATE = "start_date";
  @JsonProperty(JSON_PROPERTY_START_DATE)
  private LocalDate startDate;

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  @JsonProperty(JSON_PROPERTY_START_TIME)
  private String startTime;

  public static final String JSON_PROPERTY_END_DATE = "end_date";
  @JsonProperty(JSON_PROPERTY_END_DATE)
  private LocalDate endDate;

  public static final String JSON_PROPERTY_END_TIME = "end_time";
  @JsonProperty(JSON_PROPERTY_END_TIME)
  private String endTime;

  public static final String JSON_PROPERTY_MIN_PRICE = "min_price";
  @JsonProperty(JSON_PROPERTY_MIN_PRICE)
  private BigDecimal minPrice;

  public static final String JSON_PROPERTY_MAX_PRICE = "max_price";
  @JsonProperty(JSON_PROPERTY_MAX_PRICE)
  private BigDecimal maxPrice;

  public EventSummary id(UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Identifier for the plan (UUID)
   * @return id
   **/
  @JsonProperty(value = "id")
  @ApiModelProperty(required = true, value = "Identifier for the plan (UUID)")
  @NotNull 
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public EventSummary title(String title) {
    this.title = title;
    return this;
  }

  /**
   * Title of the plan
   * @return title
   **/
  @JsonProperty(value = "title")
  @ApiModelProperty(required = true, value = "Title of the plan")
  @NotNull 
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public EventSummary startDate(LocalDate startDate) {
    this.startDate = startDate;
    return this;
  }

  /**
   * Date when the event starts in local time
   * @return startDate
   **/
  @JsonProperty(value = "start_date")
  @ApiModelProperty(required = true, value = "Date when the event starts in local time")
  @NotNull 
  public LocalDate getStartDate() {
    return startDate;
  }

  public void setStartDate(LocalDate startDate) {
    this.startDate = startDate;
  }

  public EventSummary startTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * Time when the event starts in local time
   * @return startTime
   **/
  @JsonProperty(value = "start_time")
  @ApiModelProperty(example = "22:38:19", required = true, value = "Time when the event starts in local time")
  @NotNull 
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public EventSummary endDate(LocalDate endDate) {
    this.endDate = endDate;
    return this;
  }

  /**
   * Date when the event ends in local time
   * @return endDate
   **/
  @JsonProperty(value = "end_date")
  @ApiModelProperty(required = true, value = "Date when the event ends in local time")
  @NotNull 
  public LocalDate getEndDate() {
    return endDate;
  }

  public void setEndDate(LocalDate endDate) {
    this.endDate = endDate;
  }

  public EventSummary endTime(String endTime) {
    this.endTime = endTime;
    return this;
  }

  /**
   * Time when the event ends in local time
   * @return endTime
   **/
  @JsonProperty(value = "end_time")
  @ApiModelProperty(example = "14:45:15", required = true, value = "Time when the event ends in local time")
  @NotNull 
  public String getEndTime() {
    return endTime;
  }

  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }

  public EventSummary minPrice(BigDecimal minPrice) {
    this.minPrice = minPrice;
    return this;
  }

  /**
   * Min price from all the available tickets
   * @return minPrice
   **/
  @JsonProperty(value = "min_price")
  @ApiModelProperty(required = true, value = "Min price from all the available tickets")
  @NotNull @Valid 
  public BigDecimal getMinPrice() {
    return minPrice;
  }

  public void setMinPrice(BigDecimal minPrice) {
    this.minPrice = minPrice;
  }

  public EventSummary maxPrice(BigDecimal maxPrice) {
    this.maxPrice = maxPrice;
    return this;
  }

  /**
   * Min price from all the available tickets
   * @return maxPrice
   **/
  @JsonProperty(value = "max_price")
  @ApiModelProperty(required = true, value = "Min price from all the available tickets")
  @NotNull @Valid 
  public BigDecimal getMaxPrice() {
    return maxPrice;
  }

  public void setMaxPrice(BigDecimal maxPrice) {
    this.maxPrice = maxPrice;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventSummary eventSummary = (EventSummary) o;
    return Objects.equals(this.id, eventSummary.id) &&
        Objects.equals(this.title, eventSummary.title) &&
        Objects.equals(this.startDate, eventSummary.startDate) &&
        Objects.equals(this.startTime, eventSummary.startTime) &&
        Objects.equals(this.endDate, eventSummary.endDate) &&
        Objects.equals(this.endTime, eventSummary.endTime) &&
        Objects.equals(this.minPrice, eventSummary.minPrice) &&
        Objects.equals(this.maxPrice, eventSummary.maxPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, startDate, startTime, endDate, endTime, minPrice, maxPrice);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventSummary {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    minPrice: ").append(toIndentedString(minPrice)).append("\n");
    sb.append("    maxPrice: ").append(toIndentedString(maxPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

