package com.fever.exceptions.exception;

public enum ErrorCodes {

  BAD_GATEWAY_EXCEPTION_CODE("BAD_GATEWAY"),
  BAD_REQUEST_EXCEPTION_CODE("BAD_REQUEST"),
  CONFLICT_EXCEPTION_CODE("CONFLICT"),
  INTERNAL_SERVER_ERROR_CODE("INTERNAL_SERVER_ERROR"),
  MEDIA_TYPE_EXCEPTION_CODE("UNSUPPORTED_MEDIA_TYPE"),
  METHOD_NOT_ALLOWED_EXCEPTION_CODE("METHOD_NOT_ALLOWED"),
  FORBIDDEN_EXCEPTION_CODE("FORBIDDEN"),
  RANGE_NOT_SATISFIABLE_EXCEPTION_CODE("REQUESTED_RANGE_NOT_SATISFIABLE"),
  SERVICE_DOWN_EXCEPTION_CODE("SERVICE_UNAVAILABLE"),
  REQUEST_TIMEOUT_EXCEPTION_CODE("REQUEST_TIMEOUT"),
  RATE_LIMIT_EXCEEDED_EXCEPTION_CODE("RATE_LIMIT_EXCEEDED"),
  PRECONDITION_FAILED_EXCEPTION_CODE("PRECONDITION_FAILED"),
  NOT_ACCEPTABLE_EXCEPTION_CODE("NOT_ACCEPTABLE"),
  UNAUTHORIZED_EXCEPTION_CODE("UNAUTHORIZED"),
  UNEXPECTED_EXCEPTION_CODE("UNEXPECTED"),
  RESOURCE_NOT_FOUND("NOT_FOUND");
  private final String status;

  ErrorCodes(final String status) {
    this.status = status;
  }

  public String getStatus() {
    return status;
  }

}
