name: events-api
logLevel: debug
server:
  address: 0.0.0.0:8080
  host: 0.0.0.0
  port: 8080
version: 1.0.0
cache:
  host: "localhost"
  port: 6379
  db: 1
  enabled: true
  ttlInSeconds: 60
throttling:
  enabled: true
  capacity: 10
  intervalInSeconds: 30
mongodb:
  host: "localhost"
  port: 27017
eventsProvider:
  host: "https://provider.code-challenge.feverup.com"